# Generated by Django 4.2.3 on 2023-11-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chariman'), ('coordinator', 'Coordinator'), ('pa', 'PA to Chairman'), ('assistant-professor', 'Assistant Professor')], default='student', max_length=20),
        ),
    ]
