# Generated by Django 4.2.3 on 2023-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Chairman', 'Chariman'), ('Coordinator', 'Coordinator'), ('PA to Chairman', 'PA to Chairman'), ('Assistant Professor', 'Assistant Professor')], default='student', max_length=20),
        ),
    ]
