# Generated by Django 4.2.3 on 2023-11-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddocument',
            old_name='sender',
            new_name='sender_email',
        ),
    ]
