# Generated by Django 4.2.7 on 2023-11-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_rename_recipient_email_shareddocument_recipient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddocument',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='shareddocument',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
