# Generated by Django 4.2.3 on 2023-11-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
