# Generated by Django 4.2.3 on 2023-11-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0001_initial'),
        ('documents', '0004_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signature.signature'),
        ),
    ]
