# Generated by Django 4.2.3 on 2023-11-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signature',
        ),
    ]
