# Generated by Django 4.2.3 on 2023-11-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_remove_signature_document'),
        ('documents', '0006_remove_document_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signature.signature'),
        ),
    ]
