# Generated by Django 4.2.3 on 2023-11-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_signature'),
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document'),
        ),
    ]
